apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
 # name: ingress-service
  name: istio
  annotations:
    ingressClassName: istio
    #kubernetes.io/ingress.class: istio
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  controller: istio.io/ingress-controller    
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip-service
                port:
                  number: 5000